services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  product:
    build: ./Product.Api
    ports: 
      - 8085:80
    environment:
      - DATABASE_CONNECTION="Server=localhost;Port=5432;Database=product_db;Userid=root;Password=password;"